# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0760a351037d6c7c573606b5c7acdbeea36cf259d7fffe84f2a54c5a35be8e7f4d5b5b58fdf320c246084b64ed678153d42fc3206b3746b37f284b5e5e80b48

test:
  secret_key_base: 5089a4c18aeece5d99f0aba44418491d3d8724a4caac2d87e4b350cd1d48ebe2027d48890784680cf99d8861ef0b7d41df6f38a34c6409b0c34139d9e6b8fe9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
